title: First Github thinkgy
author: Daniel Grealy
email: dgrealy10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just your bogstandard website, nothing to see here

# social links
twitter_username: null # DO NOT include the @ character, or else the build will fail!
github_username:  dgrealy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
